// <auto-generated />
namespace PicShare.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddGeoToPicture : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddGeoToPicture));
        
        string IMigrationMetadata.Id
        {
            get { return "201412170121061_AddGeoToPicture"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
